sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"
language: scala
scala:
- 2.11.7
script:
- "./sbt compile test it:test pt:test unidoc"
#- rm conf/dev.conf Enable setup widget first
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  "gitPublish target/javaunidoc https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git
  javadoc sphere-oss automation@commercetools.de"; fi
jdk:
- oraclejdk8
env:
  matrix:
  - SBT_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1024M"
notifications:
  email:
    on_success: never
    on_failure: change
