language: scala
scala:
- 2.10.4
script:
- ./sbt cover unidoc
- if [ "$TRAVIS_BRANCH"  = "master" ]; then sbt "gitPublish target/scala-2.11/it-jacoco/html https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git coverage sphere-oss automation@commercetools.de"; fi
- if [ "$TRAVIS_BRANCH"  = "master" ]; then sbt "gitPublish target/javaunidoc https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git javadoc sphere-oss automation@commercetools.de"; fi
jdk:
- oraclejdk8
env:
  matrix:
  - SBT_OPTS="-XX:PermSize=512M -XX:MaxPermSize=1024M"
  global:
  - secure: MmhdvkSl+padAaeCJSMZMvgJRVNTQqiTLw9eyG/Yg4uZwWcOXaeeiW4+rMHr6j+JCeStoSC8NO4rbTKdnZpZuhxuKFfbslFH3oTmc4u45KxxtdMiFIf92iDAj2KVpYLmf2j23lCNyV8rq0s6wmvOtEz2DIbnDTfaiDo/68RxDSg=
  - secure: XbQrJLUKFfEsPe37YjhiAq/glXLqQxmIimgWgzoMi7D/W2g4pPNu00XbBhIBj8JrXYMyh9dTj34+1DgJFTkazHp5Vls/hxyU/y9eDk42k2vpfvcMOZEvUEmbWxfVendlRyAM1EWOQQGRE7wcQ8CKhrgixOrVtz9PjQwpF/pQUNQ=
  - secure: PDIHePa/DiW/ED/Mlwx5G1DABH2EojwUaRRPyGUPoS8jlx2bJNrqhfzKXfJAHBdd9y2bA22jQ1OPzBzu7Ui+mzPPZRVqwYSwGa61DwXsyIcCwJ4OpxzUlNORKSQiSWkTLXg31epMcFO3QibnBekQSzbbWHLC99F5uV9552goSNE=
  - SPHERE_SUNRISE_PROJECT="dummysetting"
  - SPHERE_SUNRISE_CLIENT_SECRET="dummysetting"
  - SPHERE_SUNRISE_CLIENT_ID="dummysetting"
  - secure: ocKHAWZJhmxs6tqMXtRf5mtbo671DHll91nzk2yl+bFMvhxHt5/7Y50ReLhq8Y/gXBfwA/qBAQg/ql8/q6jElg4/5T1mUdK2U153kf7FaVhDEF5ZtFbfGl+LugZAwrNGSM1+18C0ctIq87P04NU9GKY+06ZLEi95v0SS7JaRJPg=
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  buildpack: scala
  api_key:
    secure: NE6m0300BPmc8jJQbpTFyOP1uU6uK+7aVpN5lmKAPhV2gByzzq9XT3uwYqPcD9turCYujDXAmXrBzI6ISfLlrqpcxKjSupeUvvjpOxqhbpP65hA79VTuxDIajazzXrvjuKPgvUJAjD+1qdQWzoOjKJ4Y/iJ1YL+fqt8omOSFda0=
  app: sphere-sunrise
  on:
    repo: sphereio/sphere-sunrise
    branch: master
