dist: trusty
sudo: false

language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8

cache:
  # md5deep
  # - https://github.com/travis-ci/travis-ci/issues/3122
  # - https://github.com/travis-ci/travis-ci/issues/3039
  branch: md5deep
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
- sbt compile test it:test pt:test unidoc
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./sbt
  "gitPublish target/javaunidoc https://$GH_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git
  javadoc sphere-oss automation@commercetools.de"; fi

notifications:
  email:
    on_success: never
    on_failure: change
